### ISSUE TITLE
OpenBTS not getting new Neighbors apart from what GSM.Neighbors provides as default on start

### ISSUE THREAD

**Issue by AlfredAfutu** [endaga/openbts#14] opened 2015-04-17 16:46 UTC
Am having a problem with OpenBTS getting neighbors. On start of OpenBTS the Neighbors_Table is filled with GSM.Neighbors ipaddress but apart from that no new Neighbors is detected and in the logs this keeps coming up 
NeighborTable.cpp.199:addInfo: Ignoring unsolicited 'RSP NEIGHBOR PARAMS' from 127.0.0.1:16001

**Comment by shaddi** [comment] 2015-04-17 17:02
Hi there -- this is probably an issue better suited for the OpenBTS mailing list, but we'll try to answer here.

Please provide the value of your GSM.Neighbors config parameter (should be `config GSM.Neighbors` in the CLI) as well as the output of `neighbors` from your CLI. Also, please confirm you're running multiple instances of OpenBTS on separate systems that correspond to the IPs set in your GSM.Neighbors config.

**Comment by shaddi** [comment] 2015-04-17 17:04
Also -- and most importantly -- are you running OpenBTS from this repo or from the official OpenBTS repo? If you haven't built and compiled from Endaga's version of OpenBTS you should file the ticket elsewhere.

**Comment by AlfredAfutu** [comment] 2015-04-17 17:12
I am running Endaga's version of OpenBTS which i  built and compiled
GSM.Neighbors Values: 127.0.10.11:16001, 127.0.10.14:16001, 127.0.10.13:16001, 127.0.10.10:16001, 127.0.10.12:16001
neighbors values: host                              C0           BSIC
                             127.0.10.11:16001
                             127.0.10.14:16001
                             127.0.10.13:16001
                             127.0.10.10:16001
                             127.0.10.12:16001

**Comment by shaddi** [comment] 2015-04-17 17:18
Ok, got it. The IP addresses you're using are in the local subnet -- 127.0.0.0/8 -- all point to localhost. Thus, OpenBTS is looking for neighbors that are local. That won't work -- all IPs need to be other machines that are each running their own copy of OpenBTS with their own unique IPs. 

It is in theory possible to run multiple instances of OpenBTS on the same machine but in that case each instance would need to have a different `Peering.Port` specified, and you would need to properly specify the port of each instance in your neighbor configuration string. I highly recommend against this though as that type of setup is very complicated.

As configured though, the message in your log file is expected behavior.

**Comment by AlfredAfutu** [comment] 2015-04-17 17:22
So we trying to run your whitespaces code and its not working as Neighbors cannot be detected. Is there a way we can isolate the part that needs to send request to other machines?

**Comment by shaddi** [comment] 2015-04-17 17:28
If you are having issues with GSMWS, please file tickets on that [here](https://github.com/shaddi/gsmws/issues). Please note as the README there states the released code is incomplete so you will run into issues.

I'll note that getting that message is expected behavior for running GSMWS -- it's broadcasting "fake" neighbors, so those log messages will show up there. 

I'm closing this issue out as it's not a bug with this project. Feel free to continue this discussion on the GSMWS project's tracker.

**Closed by shaddi** 2015-04-17 17:28 UTC
